/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectob;
import static com.mycompany.proyectob.Proyectob.usuarios;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import java.io.File;

/**
 *
 * @author brandon
 */
public class ConsultaUsuarios extends javax.swing.JFrame {
    
    private Usuarios usuario;
    /**
     * Creates new form ConsultaUsuarios
     */
    public ConsultaUsuarios() {
        initComponents();
        Proyectob.usuarios=ArchivoUsuario.CargarUsuarios();
        //pintarTabla();
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Administrador");
        jComboBox1.addItem("Vendedor");
                
    }
    
    private void pintarTabla(){
        
    
        DefaultTableModel t=new DefaultTableModel(new String []{"Nombre","Usuario","Rol","Password"},Proyectob.usuarios.size());
        jTable1.setModel(t);
        TableModel tabla = jTable1.getModel();
        for(int i=0;i<Proyectob.usuarios.size();i++){
            Usuarios u= Proyectob.usuarios.get(i);
            tabla.setValueAt(u.getNombre(), i,0);
            tabla.setValueAt(u.getUsuario(), i,1);
            tabla.setValueAt(u.getRol(), i,2);
            tabla.setValueAt(u.getPassword(), i,3);
        }
}
    
    private void TablaXML(){
        
    
        DefaultTableModel t=new DefaultTableModel(new String []{"Nombre","Usuario","Rol","Password"},NuevoUsuario.usuarioxml.size());
        jTable1.setModel(t);
        TableModel tabla = jTable1.getModel();
        for(int i=0;i<NuevoUsuario.usuarioxml.size();i++){
            Usuarios u= NuevoUsuario.usuarioxml.get(i);
            tabla.setValueAt(u.getNombre(), i,0);
            tabla.setValueAt(u.getUsuario(), i,1);
            tabla.setValueAt(u.getRol(), i,2);
            tabla.setValueAt(u.getPassword(), i,3);
        }
}    
    
    
    public void leerxml(File Archivo){
        
        try {
           
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dbBuilder = dbFactory.newDocumentBuilder();
            Document doc = dbBuilder.parse(Archivo);
            
            doc.getDocumentElement().normalize();
            
            NodeList nList= doc.getElementsByTagName("usuario");
            
            for(int i = 0; i<nList.getLength(); i++){
                
                Node nNode= nList.item(i);
                
                if(nNode.getNodeType() == Node.ELEMENT_NODE){
                    
                    Element e = (Element) nNode;
                    Usuarios u = new Usuarios();
                    u.setNombre(e.getElementsByTagName("nombre").item(0).getTextContent());
                    u.setUsuario(e.getElementsByTagName("nombreusuario").item(0).getTextContent());
                    u.setRol(Integer.parseInt(e.getElementsByTagName("rol").item(0).getTextContent()));
                    u.setPassword(e.getElementsByTagName("password").item(0).getTextContent());
                    
                    NuevoUsuario.usuarioxml.add(u);
                    
                }
                
            }
            
            TablaXML();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Usuario");

        jLabel3.setText("Rol");

        jLabel4.setText("Password");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Cargar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "FILA" +jTable1.getSelectedRow());
        
        int borrar = jTable1.getSelectedRow();
        if(borrar>-1){
            if(borrar == 0){
                JOptionPane.showMessageDialog(this, "No puede eliminar al administrador");
            }
            else{
            
                if(JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar al usuario")==0){
                    Proyectob.usuarios.remove(borrar);
                    ArchivoUsuario.guardarUsuarios(usuarios);
                    pintarTabla();
                    JOptionPane.showMessageDialog(this, "Usuario eliminado");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un elemento a borrar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int modificar = jTable1.getSelectedRow();
        if(modificar > -1){
            
            usuario = Proyectob.usuarios.get(modificar);
            jTextField1.setText(usuario.getNombre());
            jTextField2.setText(usuario.getUsuario());
            jTextField3.setText(usuario.getPassword());
            jComboBox1.setSelectedIndex(usuario.getRol()-1);
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un elemento a modificar");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(usuario!=null){
            
            usuario.setNombre(jTextField1.getText());
            usuario.setUsuario(jTextField2.getText());

        String rol=jComboBox1.getSelectedItem().toString();
        if(rol.equals("Administrador")){
            usuario.setRol(1);
        } else {
            usuario.setRol(2);
        }
        
        //u.rol = Integer.parseInt(jTextField3.getText());
        //u.password = jTextField4.getText();
        
        String password=jTextField3.getText();
        
        boolean tam= false;
        boolean may= false;
        boolean min= false;
        boolean num= false;
        boolean especial= false;
        if(password.length()>=6){
            tam=true;
        }
        for(char c: password.toCharArray()){
            if(Character.isUpperCase(c)){
                may=true;
            } else if(Character.isLowerCase(c)){
                min=true;
            } else if(Character.isDigit(c)){
                num=true;
            } else {
                especial=true;
            }
        }
        
        
        if(tam ==true && may==true && min==true && num==true && especial==true){
            usuario.setPassword(password);
            ArchivoUsuario.guardarUsuarios(usuarios);
            JOptionPane.showMessageDialog(this, "Usuario Modificado Exitosamente.");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
        } else{
            JOptionPane.showMessageDialog(this, """
                                                Contrase\u00f1a inv\u00e1lida. Debe contener:
                                                - minimo 6 caracteres
                                                - Al menos una letra may\u00fascula
                                                - Al menos una letra min\u00fascula
                                                - Al menos un n\u00famero
                                                - Al menos un car\u00e1cter especial (@#$%^&+=!)""");
        }
            
            pintarTabla();
        } else{
            JOptionPane.showMessageDialog(this, "Valores incompletos");
        }
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser selector = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos XML", "xml");
        
        selector.setFileFilter(filtro);
        
        int seleccion = selector.showOpenDialog(this);
        
        if(seleccion == selector.APPROVE_OPTION){
            File archivo = selector.getSelectedFile();
            
            leerxml(archivo);
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
