/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectob;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author brandon
 */
public class ConsultarVenta extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarVenta
     */
    public ConsultarVenta() {
        initComponents();
        ArchivoVenta.CargarVenta();
        ArchivoLibroVenta.CargarCupon();
        pintarTabla();
        //LibrosVendios();
        
    }
    
    private void pintarTabla(){
        DefaultTableModel t=new DefaultTableModel(new String[]{"Nombre","NIT","Direccion","Total","Total sin Iva","Vendedor","Fecha"},Usuarios.Venta.size());
        jTable1.setModel(t);
        TableModel tabla=jTable1.getModel();
        for(int i=0;i<Usuarios.Venta.size();i++){
            RegistrarVenta V= Usuarios.Venta.get(i);
            tabla.setValueAt(V.getNombreCliente(), i, 0);
            tabla.setValueAt(V.getNIT(), i, 1);
            tabla.setValueAt(V.getDireecion(), i, 2);
            tabla.setValueAt(V.getTotal(), i, 3);
            tabla.setValueAt(V.getTotalsinIVA(), i, 4);
            tabla.setValueAt(V.getVendedor(), i, 5);
            tabla.setValueAt(V.getFecha(), i, 6);
        }
    }
    
       /* private void LibrosVendios(){
        DefaultTableModel t=new DefaultTableModel(new String[]{"Titulo","Precio","Cantidad","SubTotal"},RegistrarVenta.LibroVendido.size());
        jTable2.setModel(t);
        TableModel tabla=jTable2.getModel();
        for(int i=0;i<RegistrarVenta.LibroVendido.size();i++){
            LibroVenta V= RegistrarVenta.LibroVendido.get(i);
            tabla.setValueAt(V.getTitulo(), i, 0);
            tabla.setValueAt(V.getPrecio(), i, 1);
            tabla.setValueAt(V.getCantidad(), i, 2);
            tabla.setValueAt(V.getSubtotal(), i, 3);
        }
    }*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
