/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectob;

import static com.mycompany.proyectob.Proyectob.cupones;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author brandon
 */
public class NuevoCupon extends javax.swing.JFrame {
    public static LinkedList<Cupones> Cuponcsv = new LinkedList<>();

    /**
     * Creates new form NuevoCupon
     */
    public NuevoCupon() {
        initComponents();
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Porcentaje");
        jComboBox1.addItem("Monto fijo");
        
        
    }
    

        public void CargarArchivo(File Archivo){
        FileReader fr= null;
        BufferedReader br = null;
        
        try {
            fr = new FileReader(Archivo);
            br = new BufferedReader(fr);
            
            String Linea;
            while((Linea=br.readLine()) != null){
                
                String cupones []= Linea.split("\\|");
                if(cupones.length >= 4){
                    Cupones C=new Cupones();
                    C.setCodigo(cupones[0]);
                    C.setDescuento(Double.parseDouble(cupones[1]));
                    C.setTipo(cupones[2]);
                    C.setVencimiento(cupones[3]);
                    Cuponcsv.add(C);
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
        finally{
            try {
                if(fr!=null){
                    fr.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }
        
        
        public static void GuardarArchivo(String archivo){
            FileWriter fw = null;
            PrintWriter pw = null;
            
            try {
                fw = new FileWriter(archivo);
                pw = new PrintWriter(fw);
                for(Cupones c: Cuponcsv){
                    String Linea = c.getCodigo()+"|"+c.getDescuento()+"|"+c.getTipo()+"|"+c.getVencimiento()+"|";
                    pw.println(Linea);
                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            finally{
                try {
                    if(fw!=null){
                        fw.close();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } 
  /*  public static void guardarCSV(ArrayList<Cupones> lista, String Archivo){
        try(PrintWriter pw = new PrintWriter(new FileWriter(Archivo))){
            for(Cupones C : lista){
                pw.println(C.getCodigo()+"|"+C.getDescuento()+"|"+C.getTipo()+"|"+C.getVencimiento());
            }
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void cargarCSV(File Archivo){
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addColumn("Codigo");
        model.addColumn("Descuento");
        model.addColumn("Tipo");
        model.addColumn("Vencimiento");
        
        try(BufferedReader br = new BufferedReader(new FileReader(Archivo))){
            String Linea;
            while((Linea = br.readLine()) != null){
                String [] datos = Linea.split("\\|");
                model.addRow(datos);
             
            }
        } catch(IOException e){
            JOptionPane.showMessageDialog(this, e);
        }
    } */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo de cupon");

        jLabel2.setText("Tipo de descuento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Fecha de vencimiento");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Descuento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cupones C=new Cupones();
        C.setCodigo(jTextField1.getText());
        C.setDescuento(Double.parseDouble(jTextField2.getText()));
        String descuento=jComboBox1.getSelectedItem().toString();
        if(descuento.equals("Porcentaje")){
            C.setTipo(descuento);
        } else if(descuento.equals("Monto fijo")){
            C.setTipo(descuento);
        }
        
        C.setVencimiento(jTextField3.getText());
        
        Proyectob.cupones.add(C);
        GuardarArchivo("/home/brandon/Escritorio/Archivos de Cupones/Cupones.csv");
        ArchivoCupones.guardarCupon(cupones);
        //pintarTabla();
        JOptionPane.showMessageDialog(this, "Cupon agregado con exito");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
